# Generated by Django 6.1.1 on 2026-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_order_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'row', 'seat'), name='unique_flight_seat'),
        ),
    ]
